import { ArrowLeft, Braces, Coins, FileText, GitBranch, Images, ScanSearch } from "lucide-react";
import { Link } from "wouter";
import { briefSummaries, type BriefKind } from "@/lib/briefContent";

function BriefHeader({ kind }: { kind: BriefKind }) {
  const brief = briefSummaries[kind];
  return <header className="brief-header"><Link href="/" className="brief-back"><ArrowLeft size={14} /> Back to <span className="product-name">robby</span></Link><span>{brief.source}</span></header>;
}

function Section({ index, title, children }: { index: string; title: string; children: React.ReactNode }) {
  return <section className="brief-section"><span className="brief-index">{index}</span><div><h2>{title}</h2>{children}</div></section>;
}

export function HackathonBrief() {
  const brief = briefSummaries.hackathon;
  return <main className="brief-page"><BriefHeader kind="hackathon" /><section className="brief-hero"><div><p className="brief-eyebrow">SegFault 2026 · Explainable compilers</p><h1><span className="product-name">robby</span> / reverse–obverse image duality compiler</h1><p className="brief-question">What if a digital image could be a two-sided image-object, like a postcard or a coin?</p></div><aside className="brief-mark"><Braces size={28} /><span>TEXTUAL DSL → VALIDATED IR → TWO FACES</span></aside></section><section className="brief-body"><Section index="01" title="The proposition"><p><span className="product-name">robby</span> compiles a short source program into an inspectable, deterministic reverse for one immutable obverse photograph. The two faces remain mutually exclusive, like the faces of a coin.</p></Section><Section index="02" title="The constraint"><p>The obverse is an opaque byte sequence plus an RGB matrix. The compiler may hash bytes and calculate flat colour statistics, but it never identifies, classifies, or assigns meaning to depicted content.</p></Section><Section index="03" title="The system"><p>The Rust compiler parses and validates four explicit stages, lowers them to versioned JSON IR, and runs the registered seed-driven renderer only when the viewer requests a flip.</p><pre>{`base("night-street.jpg")
palette(k: 8)
reverse(mode: "negative")
output(obverse: "night-street.jpg", reverse: "transient", manifest: "transient")`}</pre></Section><Section index="04" title="The outputs"><div className="brief-output-grid"><article><Images size={18} /><strong>Obverse</strong><span>The original JPEG, unchanged.</span></article><article><ScanSearch size={18} /><strong>Reverse</strong><span>A transient PNG generated afresh for this flip.</span></article><article><GitBranch size={18} /><strong>Manifest</strong><span>Source, settings, seed, module, swatches, and output hashes.</span></article></div></Section><Section index="05" title="The practical stack"><p>One Rust library supplies the native CLI, browser WASM compiler, and deterministic renderer. The server invokes that native core and returns PNG bytes directly with a no-store response.</p></Section></section></main>;
}

export function ImageObjectBrief() {
  const brief = briefSummaries["image-object"];
  return <main className="brief-page"><BriefHeader kind="image-object" /><section className="brief-hero concept-hero"><div><p className="brief-eyebrow">MFA concept note · 2023</p><h1>{brief.title}</h1><p className="brief-question">A digital image becomes an image-object when its reverse is another image: related, distinct, and mutually exclusive in visibility.</p></div><aside className="brief-mark"><Coins size={28} /><span>OBVERSE ↔ REVERSE<br />TWO FACES · ONE OBJECT</span></aside></section><section className="brief-body"><Section index="01" title="The lost reverse"><p>Photographic prints, coins, and currency notes have sides. A print’s obverse may carry the picture, while its reverse carries stamps, edition information, and captions. The JPEG largely discarded that material relation.</p></Section><Section index="02" title="A second image, not a debug view"><p>The reverse is an independent artwork produced from declared settings, exact source identity, and numerical colour swatches. It is not a pre-rendered catalogue asset and not an interpretation of depicted content.</p></Section><Section index="03" title="Partial truths"><p>The manifest makes the computational choices inspectable without pretending that software can supply a neutral reading of the photograph. Its evidence is deliberately limited to bytes, settings, seed, module, and output.</p></Section><Section index="04" title="From reassembly to reproducibility"><p><span className="product-name">robby</span> replaces opaque or interpretive operations with a compact source language, validated IR, deterministic rendering, and a reproducibility record. Repeated identical inputs produce byte-identical results through independent executions.</p></Section><Section index="05" title="The wager"><p>Could a digital work regain the material logic of a two-sided object while making the mechanics of its reverse legible? The obverse and reverse propose an answer that can be observed—but never at the same time.</p></Section><footer className="brief-footer"><FileText size={16} /><span>{brief.source}</span></footer></section></main>;
}
