import { ArrowLeft, Braces, Coins, FileText, GitBranch, Images, ScanSearch } from "lucide-react";
import { Link } from "wouter";
import { briefSummaries, type BriefKind } from "@/lib/briefContent";

function BriefHeader({ kind }: { kind: BriefKind }) {
  const brief = briefSummaries[kind];
  return <header className="brief-header"><Link href="/" className="brief-back"><ArrowLeft size={14} /> Back to <span className="product-name">robby</span></Link><span>{brief.source}</span></header>;
}

function Section({ index, title, children }: { index: string; title: string; children: React.ReactNode }) {
  return <section className="brief-section"><span className="brief-index">{index}</span><div><h2>{title}</h2>{children}</div></section>;
}

export function HackathonBrief() {
  const brief = briefSummaries.hackathon;
  return <main className="brief-page"><BriefHeader kind="hackathon" /><section className="brief-hero"><div><p className="brief-eyebrow">SegFault 2026 · Explainable compilers</p><h1><span className="product-name">robby</span> / reverse–obverse image duality compiler</h1><p className="brief-question">What if a digital image could be a two-sided image-object, like a postcard or a coin?</p></div><aside className="brief-mark"><Braces size={28} /><span>TEXTUAL DSL → VALIDATED IR → TWO FACES</span></aside></section><section className="brief-body"><Section index="01" title="The proposition"><p><span className="product-name">robby</span> is a small compiler that turns a human-readable visual composition into a computational photograph and an inspectable reverse image. The work carries forward an artistic proposition from Mahesh Shantaram’s MFA photography research: an image may have a meaningful front and back.</p></Section><Section index="02" title="The problem"><p>Computational photography often hides how a picture is segmented, layered, transformed, and aesthetically resolved. That opacity limits artists and researchers who need to understand provenance, authorial control, and algorithmic decisions.</p></Section><Section index="03" title="The system"><p>A concise composition language names a base image, content images, masks, placement, and reverse mode. The compiler parses and validates the source, lowers it into JSON IR, and executes a legible pipeline.</p><pre>{`base("night-street.jpg")
  |> cutout(source: "rider-01.jpg", object: person)
  |> place(x: 0.62, y: 0.48, blend: "multiply")
  |> reverse(mode: "provenance-map")`}</pre></Section><Section index="04" title="The outputs"><div className="brief-output-grid"><article><Images size={18} /><strong>Obverse</strong><span>A computational photograph.</span></article><article><ScanSearch size={18} /><strong>Reverse</strong><span>A related, distinct, mutually exclusive audit-artwork.</span></article><article><GitBranch size={18} /><strong>Manifest</strong><span>An inspectable process graph with source and output evidence.</span></article></div></Section><Section index="05" title="The practical stack"><p>Rust provides the parser and compiler core; JSON is the intermediate representation; Python executes image operations; and the web application makes the obverse, reverse, and transformation lineage legible together.</p></Section></section></main>;
}

export function ImageObjectBrief() {
  const brief = briefSummaries["image-object"];
  return <main className="brief-page"><BriefHeader kind="image-object" /><section className="brief-hero concept-hero"><div><p className="brief-eyebrow">MFA concept note · 2023</p><h1>{brief.title}</h1><p className="brief-question">A digital image becomes an image-object when its reverse is another image: related, distinct, and mutually exclusive in visibility.</p></div><aside className="brief-mark"><Coins size={28} /><span>OBVERSE ↔ REVERSE<br />TWO FACES · ONE OBJECT</span></aside></section><section className="brief-body"><Section index="01" title="The lost reverse"><p>Photographic prints, coins, and currency notes have sides. A print’s obverse may carry the picture, while its reverse carries stamps, edition information, and captions. When the physical print gave way to the JPEG, that two-sided logic largely disappeared.</p></Section><Section index="02" title="A second image, not a debug view"><p>The reverse need not be hidden implementation residue. It can be another image with its own aesthetic and evidentiary force: a palette audit, a provenance map, or an account of the transformations that produced the obverse.</p></Section><Section index="03" title="Partial truths"><p>Computational imaging expands photography’s rhetorical toolbox. Rather than claiming a single neutral record, an image-object can expose the partial choices involved in masking, layering, framing, and rendering—making the process available for both critique and play.</p></Section><Section index="04" title="From reassembly to accountability"><p>In the precursor system, source images were analyzed for significant objects, cut apart, and reassembled into a composition. <span className="product-name">robby</span> preserves that productive tension while replacing opaque randomness with source text, validated IR, credentials, and an inspectable process graph.</p></Section><Section index="05" title="The wager"><p>Could a digital work become even better than the real thing by regaining the material logic of a two-sided object while making the algorithmic decisions of its making visible? The obverse and reverse propose an answer that can be observed—but never at the same time.</p></Section><footer className="brief-footer"><FileText size={16} /><span>{brief.source}</span></footer></section></main>;
}
